# Generated by Django 5.2 on 2025-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semister',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semister',
            field=models.IntegerField(default=1),
        ),
    ]
