# Generated by Django 5.2 on 2025-04-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analizer', '0002_subject_semister_alter_exam_semister'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='question_papers/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='Analizer.subject')),
            ],
        ),
    ]
