# Generated by Django 5.2 on 2025-04-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analizer', '0006_chat_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
