# Generated by Django 5.2 on 2025-04-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analizer', '0007_remove_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Analizer.questionpaper'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
